name: Godot Headless Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  headless-check:
    name: Headless Project Check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot binary
        id: godot-cache
        uses: actions/cache@v3
        with:
          path: godot
          key: godot-4.4.1-linux

      - name: Download Godot if not cached
        if: steps.godot-cache.outputs.cache-hit != 'true'
        run: |
          wget -O godot.zip https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.4.1-stable_linux.x86_64

      - name: Disable GitPlugin in CI (temporary change)
        run: |
           sed -i 's/^vcs_name="GitPlugin"/vcs_name=""/' project.godot

      - name: Run headless project load (smoke test)
        run: |
          ./godot/Godot_v4.4.1-stable_linux.x86_64  \
            --headless --editor --quit --path .

      - name: Run runtime + lint test script
        run: |
          ./godot/Godot_v4.4.1-stable_linux.x86_64  \ 
            --headless --rendering-driver opengl3 --script res://tests/test_runtime_errors.gd --path .
