name: Godot Headless Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  headless-check:
    name: Headless Project Check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot binary
        id: godot-cache
        uses: actions/cache@v3
        with:
          path: godot
          key: godot-4.4.1-linux

      - name: Download Godot if not cached
        if: steps.godot-cache.outputs.cache-hit != 'true'
        run: |
          wget -O godot.zip https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.4.1-stable_linux.x86_64

      - name: Headless smoke test with filtered error check
        run: |
          mkdir -p .godot_ci_config

          ./godot/Godot_v4.4.1-stable_linux.x86_64 \
            --headless --editor --quit --path . \
            --editor-settings-path .godot_ci_config \
            | tee raw_godot.log

          grep -v -E "ERROR: Cannot get class 'GitPlugin'|ERROR: Received a nullptr VCS extension" raw_godot.log > godot_clean.log

          if grep -E "ERROR:|SCRIPT ERROR|Parse error|Failed loading resource|Failed to load script|Invalid call|Attempt to call function on null instance|Invalid get index|Invalid set index" godot_clean.log > matches.log; then
            echo "::error title=Godot Check::Detected critical error in Godot project"
            cat matches.log
            exit 1
          else
            echo "✅ No critical Godot errors found."
          fi
